#!/usr/bin/env python3
"""Generate and update the repository-level CHANGELOG.md."""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path


def run_git(repo_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(repo_root), *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout.strip()


def list_tags(repo_root: Path) -> list[str]:
    output = run_git(repo_root, "tag", "--list", "v*", "--sort=version:refname")
    return [line.strip() for line in output.splitlines() if line.strip()]


def render_release_notes(
    repo_root: Path,
    from_ref: str,
    to_ref: str,
    title: str,
) -> str:
    script_path = repo_root / "scripts" / "release_notes.py"
    with tempfile.NamedTemporaryFile(
        mode="w+", encoding="utf-8", delete=False
    ) as handle:
        temp_path = Path(handle.name)

    try:
        command = [
            sys.executable,
            str(script_path),
            "--repo-root",
            str(repo_root),
            "--to",
            to_ref,
            "--title",
            title,
            "--output",
            str(temp_path),
        ]
        if from_ref:
            command.extend(["--from", from_ref])
        else:
            command.append("--draft")

        subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        content = temp_path.read_text(encoding="utf-8")
    finally:
        temp_path.unlink(missing_ok=True)

    lines = content.splitlines()
    if lines and lines[0].startswith("# "):
        lines[0] = f"## {title}"
    elif lines:
        lines.insert(0, f"## {title}")

    normalized_lines = [
        line for line in lines if not line.startswith("- Generated at:")
    ]

    return "\n".join(normalized_lines).rstrip() + "\n"


def build_changelog(repo_root: Path) -> str:
    tags = list_tags(repo_root)
    sections: list[str] = [
        "# Changelog",
        "",
        "This file is automatically generated from Git tags and Conventional Commits.",
        "",
    ]

    if tags:
        unreleased = render_release_notes(repo_root, "", "HEAD", "Unreleased")
        sections.append(unreleased.rstrip())
        sections.append("")

        previous_tag = ""
        release_sections: list[str] = []
        for tag in tags:
            section = render_release_notes(repo_root, previous_tag, tag, tag)
            release_sections.append(section.rstrip())
            previous_tag = tag

        for section in reversed(release_sections):
            sections.append(section)
            sections.append("")
    else:
        sections.append("## Unreleased")
        sections.append("")
        sections.append("No release tags have been created yet.")
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the repository-level CHANGELOG.md."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root (default: .)")
    parser.add_argument(
        "--output",
        default="CHANGELOG.md",
        help="Write the generated changelog to a file (default: CHANGELOG.md)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated changelog to stdout instead of writing a file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    markdown = build_changelog(repo_root)

    if args.stdout:
        sys.stdout.write(markdown)
        return 0

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = repo_root / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
